### ISSUE TITLE
Combine efforts with other bats-assert libraries?

### ISSUE THREAD

**Issue by Potherca** [jasonkarns/bats-assert#6]
Currently there are 3 separate libraries that offer assertions for BATS.

These are:

- [jasonkarns/bats-assert](https://github.com/jasonkarns/bats-assert) (https://github.com/jasonkarns/bats-assert/issues/6)
- [thingsym/bats-assertion](https://github.com/thingsym/bats-assertion) (https://github.com/thingsym/bats-assertion/issues/1)
- [ztombol/bats-assert](https://github.com/ztombol/bats-assert) (https://github.com/ztombol/bats-assert/issues/21)

Each library has a different set of assert/refute functions.

I have made a [comparison of the functions each project offers](https://gist.github.com/Potherca/0df1169470c235be7bb921943b15f637).

To avoid duplicating effort and offer as much functionality to users as possible, would any form of collaboration be possible?

As a side note, would a (combined?) `bats-asserts` library not be better suited to live under the @bats-core organisation? (https://github.com/bats-core/bats-core/issues/44)

**Comment by jasonkarns** [comment]
Closing this as, yes, I'm deprecating this repo in favor of ztombol's variant. However, it appears as though ztombol has gone dark on github. So I've actually forked their bats-assert to: [jasonkarns/bats-assert-1](https://github.com/jasonkarns/bats-assert-1) where I will attempt to resolve a couple of the open issues and PRs, perhaps incorporating work from [thingsym/bats-assertion](https://github.com/thingsym/bats-assertion)

Eventually I hope to have this repo pulled under the [bats-core org](https://github.com/bats-core).
